# Generated by Django 5.1 on 2026-02-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=240)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("opening_hours", models.CharField(blank=True, max_length=120)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="salons/logos/")),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="salons/covers/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="salons", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="SalonFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, help_text="Example: scissors", max_length=40)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="features", to="salon.salon")),
            ],
            options={"ordering": ("display_order", "id")},
        ),
        migrations.CreateModel(
            name="SalonPageConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hero_title", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle", models.TextField(blank=True)),
                ("cta_text", models.CharField(default="Book Appointment", max_length=60)),
                ("cta_link", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#d97706", max_length=7)),
                ("secondary_color", models.CharField(default="#1f2937", max_length=7)),
                ("background_style", models.CharField(choices=[("warm", "Warm"), ("cool", "Cool"), ("light", "Light")], default="warm", max_length=20)),
                ("show_feature_icons", models.BooleanField(default=True)),
                ("custom_css", models.TextField(blank=True)),
                ("salon", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="page_config", to="salon.salon")),
            ],
        ),
        migrations.CreateModel(
            name="SalonService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="services", to="salon.salon")),
            ],
            options={"ordering": ("display_order", "name")},
        ),
    ]
