# Generated by Django 5.1 on 2026-02-17 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonpageconfig",
            name="layout_style",
            field=models.CharField(
                choices=[("classic", "Classic"), ("cards", "Cards"), ("minimal", "Minimal")],
                default="classic",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=160)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("last_visit", models.DateField(blank=True, null=True)),
                ("total_visits", models.PositiveIntegerField(default=0)),
                ("total_spend", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_vip", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customers", to="salon.salon")),
            ],
            options={
                "ordering": ("-total_spend", "full_name"),
                "unique_together": {("salon", "phone")},
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("discount_percent", models.PositiveIntegerField(default=10)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="salon.salon")),
            ],
            options={"ordering": ("-valid_from", "title")},
        ),
        migrations.CreateModel(
            name="WhatsAppCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                (
                    "target_filter",
                    models.CharField(
                        choices=[
                            ("all", "All customers"),
                            ("vip", "VIP customers"),
                            ("high_spend", "High spenders"),
                            ("inactive_60", "Inactive for 60 days"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("offer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="salon.offer")),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="salon.salon")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="SalonVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("visit_date", models.DateField()),
                ("amount_paid", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="visits", to="salon.customer")),
                ("offer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="salon.offer")),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="visits", to="salon.salon")),
                ("service", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="salon.salonservice")),
            ],
            options={"ordering": ("-visit_date", "-id")},
        ),
    ]
