# Generated by Django 5.1 on 2026-02-17 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0002_customer_offer_salonvisit_whatsappcampaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonpageconfig",
            name="custom_font",
            field=models.CharField(
                choices=[
                    ("poppins", "Poppins"),
                    ("lora", "Lora"),
                    ("montserrat", "Montserrat"),
                    ("playfair", "Playfair Display"),
                ],
                default="poppins",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salonpageconfig",
            name="theme_preset",
            field=models.CharField(
                choices=[("sunset", "Sunset"), ("forest", "Forest"), ("ocean", "Ocean"), ("rose", "Rose")],
                default="sunset",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BeforeAfterGallery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=160)),
                ("before_image", models.ImageField(upload_to="salons/gallery/before/")),
                ("after_image", models.ImageField(upload_to="salons/gallery/after/")),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="before_after_items", to="salon.salon")),
            ],
            options={"ordering": ("display_order", "id")},
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(max_length=120)),
                ("text", models.TextField()),
                ("rating", models.PositiveIntegerField(default=5)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="testimonials", to="salon.salon")),
            ],
            options={"ordering": ("display_order", "id")},
        ),
        migrations.CreateModel(
            name="WebsiteSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section_type", models.CharField(choices=[("about", "About"), ("promo", "Promo"), ("custom", "Custom")], default="custom", max_length=20)),
                ("heading", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="website_sections", to="salon.salon")),
            ],
            options={"ordering": ("display_order", "id")},
        ),
    ]
