# Generated by Django 5.1 on 2026-02-17 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0003_beforeaftergallery_testimonial_websitesection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSBill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bill_number", models.CharField(max_length=30, unique=True)),
                ("bill_date", models.DateTimeField(auto_now_add=True)),
                ("payment_method", models.CharField(choices=[("cash", "Cash"), ("upi", "UPI"), ("card", "Card"), ("mixed", "Mixed")], default="cash", max_length=20)),
                ("payment_status", models.CharField(choices=[("paid", "Paid"), ("partial", "Partially Paid"), ("pending", "Pending")], default="paid", max_length=20)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("tax_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("amount_received", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("balance_due", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pos_bills", to="salon.customer")),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pos_bills", to="salon.salon")),
            ],
            options={"ordering": ("-bill_date", "-id")},
        ),
        migrations.CreateModel(
            name="POSBillItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_name", models.CharField(max_length=160)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="salon.posbill")),
                ("service", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="salon.salonservice")),
            ],
            options={"ordering": ("id",)},
        ),
    ]
