# Generated by Django 5.1 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0004_posbill_posbillitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="upi_id",
            field=models.CharField(blank=True, help_text="Example: mysalon@okhdfcbank", max_length=120),
        ),
        migrations.AddField(
            model_name="salon",
            name="upi_payee_name",
            field=models.CharField(blank=True, help_text="Name shown in UPI payment apps", max_length=120),
        ),
    ]

