# Generated by Django 5.1 on 2026-02-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0005_salon_upi_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(blank=True, max_length=160)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("appointment_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("booked", "Booked"), ("completed", "Completed"), ("cancelled", "Cancelled"), ("no_show", "No Show")],
                        default="booked",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="appointments", to="salon.customer"),
                ),
                (
                    "salon",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="salon.salon"),
                ),
                (
                    "service",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="appointments", to="salon.salonservice"),
                ),
            ],
            options={
                "ordering": ("appointment_at", "-id"),
            },
        ),
    ]

