# Generated by Django 5.1 on 2026-02-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0006_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_date", models.DateField()),
                (
                    "entry_type",
                    models.CharField(choices=[("expense", "Expense"), ("other_income", "Other Income")], default="expense", max_length=20),
                ),
                ("title", models.CharField(max_length=160)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profit_entries", to="salon.salon")),
            ],
            options={"ordering": ("-entry_date", "-id")},
        ),
    ]

