# Generated by Django 5.1 on 2026-02-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0007_profitentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=140)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("payment_mode", models.CharField(choices=[("fixed", "Monthly Fixed"), ("commission", "Commission Based")], default="fixed", max_length=20)),
                ("fixed_monthly_salary", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("commission_percent", models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workers", to="salon.salon")),
            ],
            options={
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="WorkerSalaryPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_month", models.PositiveIntegerField()),
                ("period_year", models.PositiveIntegerField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_on", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("salon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="worker_salary_payments", to="salon.salon")),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="salary_payments", to="salon.worker")),
            ],
            options={
                "ordering": ("-paid_on", "-id"),
            },
        ),
        migrations.AddField(
            model_name="salonvisit",
            name="assigned_worker",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="visits", to="salon.worker"),
        ),
    ]

