# Generated by Django 5.1 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0008_worker_workersalarypayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="aadhaar_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="worker",
            name="address_line1",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="worker",
            name="address_line2",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="worker",
            name="city",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="worker",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="worker",
            name="pincode",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="worker",
            name="state",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]

