# Generated by Django 5.1 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0009_worker_kyc_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="aadhaar_image",
            field=models.ImageField(blank=True, null=True, upload_to="workers/kyc/aadhaar/"),
        ),
        migrations.AddField(
            model_name="worker",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worker",
            name="pan_image",
            field=models.ImageField(blank=True, null=True, upload_to="workers/kyc/pan/"),
        ),
    ]

