# Generated by Django 5.1 on 2026-02-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0010_worker_audit_and_kyc_docs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="can_login",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worker",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worker_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

