# Generated by Django 5.1 on 2026-02-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_alter_salon_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonvisit',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='visit_records', to='salon.salonservice'),
        ),
    ]
