# Generated by Django 5.1 on 2026-02-22 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_backfill_salonvisit_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lifetime_points',
            field=models.PositiveIntegerField(default=0, help_text='Total points earned all time'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='Current loyalty points balance'),
        ),
        migrations.AddField(
            model_name='posbill',
            name='points_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount from redeemed points', max_digits=10),
        ),
        migrations.AddField(
            model_name='posbill',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty points earned from this bill'),
        ),
        migrations.AddField(
            model_name='posbill',
            name='points_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty points redeemed for discount'),
        ),
        migrations.AddField(
            model_name='posbill',
            name='receipt_sent',
            field=models.BooleanField(default=False, help_text='Whether digital receipt has been sent'),
        ),
        migrations.AddField(
            model_name='posbill',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, help_text='When receipt was sent', null=True),
        ),
        migrations.AddField(
            model_name='posbill',
            name='receipt_sent_via',
            field=models.CharField(blank=True, help_text='How receipt was sent (whatsapp/email)', max_length=20),
        ),
        migrations.CreateModel(
            name='LoyaltyPointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('redeemed', 'Points Redeemed'), ('expired', 'Points Expired'), ('adjusted', 'Points Adjusted')], default='earned', max_length=20)),
                ('points', models.PositiveIntegerField(help_text='Points added (positive) or deducted (negative)')),
                ('balance_after', models.PositiveIntegerField(help_text='Points balance after this transaction')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='salon.posbill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='salon.customer')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='salon.salon')),
            ],
            options={
                'verbose_name': 'Loyalty Points Transaction',
                'verbose_name_plural': 'Loyalty Points Transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SalonLoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_rupee', models.DecimalField(decimal_places=2, default=1, help_text='Points earned per Rs.1 spent', max_digits=5)),
                ('points_redeem_value', models.DecimalField(decimal_places=2, default=0.25, help_text='Rs. value per point when redeemed', max_digits=5)),
                ('min_points_to_redeem', models.PositiveIntegerField(default=100, help_text='Minimum points required to redeem')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_settings', to='salon.salon')),
            ],
        ),
    ]
