# Generated by Django 5.1 on 2026-02-24 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0015_customer_lifetime_points_customer_loyalty_points_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerDashboardSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "layout_style",
                    models.CharField(
                        choices=[
                            ("mixed", "Mixed Dashboard"),
                            ("pivot_grid", "Pivot Grid Focus"),
                            ("histogram", "Histogram Focus"),
                            ("pie", "Pie Focus"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                ("show_pivot", models.BooleanField(default=True)),
                ("show_histogram", models.BooleanField(default=True)),
                ("show_pie", models.BooleanField(default=True)),
                ("show_leaderboard", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_dashboard_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
