# Generated by Django 5.1 on 2026-02-24 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0017_taskentry_userreminderpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonpageconfig",
            name="accent_color",
            field=models.CharField(default="#0f766e", max_length=7),
        ),
        migrations.AddField(
            model_name="salonpageconfig",
            name="dashboard_theme",
            field=models.CharField(
                choices=[
                    ("signature", "Signature"),
                    ("luxury", "Luxury"),
                    ("vibrant", "Vibrant"),
                    ("minimal", "Minimal"),
                ],
                default="signature",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salonpageconfig",
            name="owner_background",
            field=models.CharField(
                choices=[("aurora", "Aurora"), ("mesh", "Mesh"), ("pearl", "Pearl"), ("charcoal", "Charcoal")],
                default="aurora",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salonpageconfig",
            name="sidebar_variant",
            field=models.CharField(
                choices=[("glass", "Glass"), ("solid", "Solid"), ("minimal", "Minimal")],
                default="glass",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salonpageconfig",
            name="visual_intensity",
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.CreateModel(
            name="StyleConsultation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(blank=True, max_length=140)),
                ("gender", models.CharField(choices=[("male", "Male"), ("female", "Female"), ("other", "Other")], default="male", max_length=20)),
                (
                    "face_shape",
                    models.CharField(
                        choices=[
                            ("oval", "Oval"),
                            ("round", "Round"),
                            ("square", "Square"),
                            ("heart", "Heart"),
                            ("diamond", "Diamond"),
                            ("long", "Long"),
                        ],
                        default="oval",
                        max_length=20,
                    ),
                ),
                (
                    "hair_texture",
                    models.CharField(
                        choices=[("straight", "Straight"), ("wavy", "Wavy"), ("curly", "Curly"), ("coily", "Coily")],
                        default="straight",
                        max_length=20,
                    ),
                ),
                ("hair_length", models.CharField(choices=[("short", "Short"), ("medium", "Medium"), ("long", "Long")], default="short", max_length=20)),
                (
                    "skin_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("dry", "Dry"),
                            ("oily", "Oily"),
                            ("combination", "Combination"),
                            ("sensitive", "Sensitive"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "beard_preference",
                    models.CharField(
                        choices=[("clean", "Clean Shave"), ("stubble", "Stubble"), ("boxed", "Boxed Beard"), ("full", "Full Beard")],
                        default="clean",
                        max_length=20,
                    ),
                ),
                ("concern_notes", models.TextField(blank=True)),
                ("reference_image", models.ImageField(upload_to="style_advisor/")),
                ("suggested_haircut", models.CharField(blank=True, max_length=160)),
                ("suggested_beard", models.CharField(blank=True, max_length=160)),
                ("suggested_facial", models.CharField(blank=True, max_length=160)),
                ("suggested_scrub", models.CharField(blank=True, max_length=160)),
                ("selected_style", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "salon",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="style_consultations", to="salon.salon"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="style_consultations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
