# Generated by Django 5.1 on 2026-02-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0018_salonpageconfig_advanced_and_styleconsultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="birthday_coupon_sent_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="membership_tier",
            field=models.CharField(
                choices=[("bronze", "Bronze"), ("silver", "Silver"), ("gold", "Gold"), ("platinum", "Platinum")],
                default="bronze",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="referral_credits",
            field=models.PositiveIntegerField(default=0, help_text="Referral credits available for redemption"),
        ),
        migrations.AddField(
            model_name="customer",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="salon.customer",
            ),
        ),
        migrations.AddField(
            model_name="salonloyaltysettings",
            name="birthday_coupon_discount_percent",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="salonloyaltysettings",
            name="birthday_coupon_valid_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="salonloyaltysettings",
            name="enable_membership_tiers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salonloyaltysettings",
            name="gold_tier_min_points",
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AddField(
            model_name="salonloyaltysettings",
            name="platinum_tier_min_points",
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name="salonloyaltysettings",
            name="referral_bonus_points",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="salonloyaltysettings",
            name="silver_tier_min_points",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="styleconsultation",
            name="suggestion_source",
            field=models.CharField(default="rule", max_length=20),
        ),
        migrations.CreateModel(
            name="BirthdayCoupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("discount_percent", models.PositiveIntegerField(default=10)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("is_redeemed", models.BooleanField(default=False)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="birthday_coupons", to="salon.customer"),
                ),
                (
                    "salon",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="birthday_coupons", to="salon.salon"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
