# Generated by Django 5.1 on 2026-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0019_loyalty_rewards_and_style_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonvisit",
            name="points_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="salonvisit",
            name="points_redeemed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
