# Generated by Django 5.1 on 2026-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0020_salonvisit_points_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="styleconsultation",
            name="transformed_preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="style_advisor/previews/"),
        ),
    ]
