# Generated by Django 5.1 on 2026-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0021_styleconsultation_transformed_preview_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonfeature",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="salons/features/"),
        ),
        migrations.AddField(
            model_name="salonservice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="salons/services/"),
        ),
    ]
