# Generated by Django 5.1 on 2026-02-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0022_salonfeature_image_salonservice_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_name", models.CharField(max_length=160)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "Pieces"),
                            ("g", "Grams"),
                            ("kg", "Kilograms"),
                            ("ml", "Milliliters"),
                            ("l", "Liters"),
                            ("box", "Box"),
                        ],
                        default="pcs",
                        max_length=20,
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("purchase_date", models.DateField()),
                ("mark_as_expense", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_entries",
                        to="salon.salon",
                    ),
                ),
            ],
            options={
                "ordering": ("-purchase_date", "-id"),
            },
        ),
    ]
