# Generated by Django 5.1 on 2026-02-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0023_inventoryentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportBuilderSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "layout_style",
                    models.CharField(
                        choices=[
                            ("balanced", "Balanced"),
                            ("financial_focus", "Financial Focus"),
                            ("inventory_focus", "Inventory Focus"),
                        ],
                        default="balanced",
                        max_length=30,
                    ),
                ),
                ("show_metrics_summary", models.BooleanField(default=True)),
                ("show_entry_forms", models.BooleanField(default=True)),
                ("show_profit_entries", models.BooleanField(default=True)),
                ("show_inventory_list", models.BooleanField(default=True)),
                ("show_monthly_inventory", models.BooleanField(default=True)),
                ("show_sales_bills", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "salon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_builder_setting",
                        to="salon.salon",
                    ),
                ),
            ],
        ),
    ]
