# Generated by Django 5.1 on 2026-02-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0024_reportbuildersetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_collections_donut",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_expense_donut",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_kpi_strip",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_mini_cards",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_sales_expense_chart",
            field=models.BooleanField(default=True),
        ),
    ]
