# Generated by Django 5.1 on 2026-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0025_reportbuildersetting_chart_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_metric_customers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_metric_expense",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_metric_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_metric_loss",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_metric_profit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportbuildersetting",
            name="show_metric_workers",
            field=models.BooleanField(default=True),
        ),
    ]
