# Generated by Django 5.1 on 2026-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0026_reportbuildersetting_metric_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="salonpageconfig",
            name="website_bg_color",
            field=models.CharField(default="#f8fafc", max_length=7),
        ),
        migrations.AddField(
            model_name="salonpageconfig",
            name="website_wallpaper",
            field=models.ImageField(blank=True, null=True, upload_to="salons/wallpapers/"),
        ),
    ]
