# Generated by Django 5.1 on 2026-02-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0027_salonpageconfig_website_bg_and_wallpaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="salon",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
