# Generated by Django 5.1 on 2026-03-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0030_salon_location_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerIncentiveCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_incentive_campaigns', to='salon.salon')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
