# Generated by Django 5.1 on 2026-03-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0031_workerincentivecampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='nav_color',
            field=models.CharField(default='#1d4ed8', max_length=7),
        ),
    ]
