# Generated by Django 5.1 on 2026-03-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0032_worker_nav_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='nav_background_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AddField(
            model_name='worker',
            name='nav_text_color',
            field=models.CharField(default='#eff6ff', max_length=7),
        ),
    ]
