# Generated by Django 5.1 on 2026-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0034_usermobileprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='msg91', max_length=40, unique=True)),
                ('auth_key', models.CharField(blank=True, max_length=255)),
                ('sms_template_id', models.CharField(blank=True, max_length=120)),
                ('whatsapp_template_id', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(default='91', max_length=6)),
                ('timeout_seconds', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Messaging Gateway Config',
                'verbose_name_plural': 'Messaging Gateway Config',
            },
        ),
    ]
