# Generated by Django 5.1 on 2026-03-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0036_passwordresetotplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotplog',
            name='provider_request_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
