# Generated by Django 5.1 on 2024-09-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.TextField(max_length=100)),
                ('last', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
