# Generated by Django 5.1 on 2025-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='number_plate',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default=1234, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
